Fix missing net/smtp error
```
Error:
LayoutsTest#test_no_layout:
LoadError: cannot load such file -- net/smtp
    activesupport (6.1.6) lib/active_support/dependencies.rb:332:in `require'
    activesupport (6.1.6) lib/active_support/dependencies.rb:332:in `block in require'
    activesupport (6.1.6) lib/active_support/dependencies.rb:299:in `load_dependency'
    activesupport (6.1.6) lib/active_support/dependencies.rb:332:in `require'
    mail (2.7.1) lib/mail.rb:9:in `<module:Mail>'
```

https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp