Rails 7 support and migrating away from Travis (#61)
* Update maintenance policy and dummy gemfiles

* Update check changelog

* First Github CI commit

* Fix missing net/smtp error

```
Error:
LayoutsTest#test_no_layout:
LoadError: cannot load such file -- net/smtp
    activesupport (6.1.6) lib/active_support/dependencies.rb:332:in `require'
    activesupport (6.1.6) lib/active_support/dependencies.rb:332:in `block in require'
    activesupport (6.1.6) lib/active_support/dependencies.rb:299:in `load_dependency'
    activesupport (6.1.6) lib/active_support/dependencies.rb:332:in `require'
    mail (2.7.1) lib/mail.rb:9:in `<module:Mail>'
```

https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp

* Patch for Rails 7

Documented in https://github.com/zombocom/maildown/issues/59. This class was removed from Rails 7.

This causes an error on this line when trying to alias a method that does not exist https://github.com/zombocom/maildown/blob/cbf5b51e0867eab1ec945d38b5335f42139b0322/lib/maildown/ext/action_view.rb#L7.

The solution presented was to re-add the method. However simply doing this with a `defined?(OptimizedFileSystemResolver)` causes a load via zeitwork and also results in a crash.

The presence of this code appears to do nothing in Rails 7. It's basically a no-op that allows us to boot without erroring.